package eg.enums;

public enum Specialization {
    CARDIOLOGY,
    DERMATOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    GYNECOLOGY,
    HEMATOLOGY,
    NEPHROLOGY,
    NEUROLOGY,
    ONCOLOGY,
    OPHTHALMOLOGY,
    ORTHOPEDICS,
    OTOLARYNGOLOGY,
    PEDIATRICS,
    PSYCHIATRY,
    PULMONOLOGY,
    RHEUMATOLOGY,
    UROLOGY
}
