create table city
(
    id              bigint generated by default as identity,
    governorate_id  bigint,
    name_ar         varchar(255) not null,
    name_en         varchar(255) not null,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    "created_by_id" bigint,
    "updated_by_id" bigint,
    primary key (id)
);

create table doctor
(
    id              bigint generated by default as identity,
    first_name      varchar(255) not null,
    last_name       varchar(255) not null,
    address         varchar(255) not null,
    clinic_phone    varchar(255) not null,
    phone           varchar(255),
    specialization  varchar(255) not null check (specialization in
                                                 ('CARDIOLOGY', 'DERMATOLOGY', 'ENDOCRINOLOGY', 'GASTROENTEROLOGY',
                                                  'GYNECOLOGY', 'HEMATOLOGY', 'NEPHROLOGY', 'NEUROLOGY', 'ONCOLOGY',
                                                  'OPHTHALMOLOGY', 'ORTHOPEDICS', 'OTOLARYNGOLOGY', 'PEDIATRICS',
                                                  'PSYCHIATRY', 'PULMONOLOGY', 'RHEUMATOLOGY', 'UROLOGY')),
    doctor_class_id bigint,
    is_deleted      boolean,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    "created_by_id" bigint,
    "updated_by_id" bigint,
    primary key (id)
);

create table doctor_class
(
    id              bigint generated by default as identity,
    name            varchar(255) not null,
    notes           varchar(255),
    visit_count     integer      not null,
    is_active       boolean,
    is_deleted      boolean,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    "created_by_id" bigint,
    "updated_by_id" bigint,
    primary key (id)
);

create table governorate
(
    id              bigint generated by default as identity,
    name_ar         varchar(255) not null,
    name_en         varchar(255) not null,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    "created_by_id" bigint,
    "updated_by_id" bigint,
    primary key (id)
);

create table medicine
(
    id                bigint generated by default as identity,
    active_ingredient varchar(255),
    barcode           varchar(255) not null,
    description       varchar(255) not null,
    name              varchar(255) not null,
    notes             varchar(255),
    price             float(53)    not null,
    type              varchar(255) check (type in
                                          ('TABLET', 'SYRUP', 'INJECTION', 'CAPSULE', 'DROPS', 'OINTMENT', 'CREAM',
                                           'GEL', 'LOTION', 'POWDER', 'INHALER', 'SPRAY', 'SUPPOSITORY', 'IMPLANT')),
    is_deleted        boolean,
    created_at        timestamp(6),
    updated_at        timestamp(6),
    "created_by_id"   bigint unique,
    "updated_by_id"   bigint unique,
    primary key (id)
);

create table permission
(
    id              bigint generated by default as identity,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    "created_by_id" bigint,
    "updated_by_id" bigint,
    primary key (id)
);

create table pharmacy
(
    id              bigint generated by default as identity,
    name            varchar(255) not null,
    owner           varchar(255) not null,
    address         varchar(255) not null,
    phone           varchar(255) not null,
    is_deleted      boolean,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    "created_by_id" bigint,
    "updated_by_id" bigint,
    primary key (id)
);

create table role
(
    id          bigint generated by default as identity,
    name        varchar(255) not null unique,
    description varchar(255),
    is_deleted  boolean,
    primary key (id)
);

create table "user"
(
    id              bigint generated by default as identity,
    username        varchar(255) not null unique,
    first_name      varchar(255) not null,
    last_name       varchar(255) not null,
    gender          varchar(255) check (gender in ('MALE', 'FEMALE')),
    email           varchar(255),
    password        varchar(255) not null,
    phone           varchar(11)  not null unique,
    role_id         bigint,
    is_deleted      boolean,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    "created_by_id" bigint,
    "updated_by_id" bigint,
    primary key (id)
);

alter table if exists city
    add constraint FKlumublcje2l6svyrm9ps0kyi6
    foreign key ("created_by_id")
    references "user";

alter table if exists city
    add constraint FKrepiakoweh0bna79m599brp6p
    foreign key ("updated_by_id")
    references "user";

alter table if exists city
    add constraint FK9i8dl00b2gdgo5nmwkj6egipd
    foreign key (governorate_id)
    references governorate;

alter table if exists doctor
    add constraint FKoudx5ku2170q9t9pj4uibolpx
    foreign key ("created_by_id")
    references "user";

alter table if exists doctor
    add constraint FKr4jojo04ka6wrthn3yrnrtw1i
    foreign key ("updated_by_id")
    references "user";

alter table if exists doctor
    add constraint FK3he0r56v0sm0t8dlprgdk4m29
    foreign key (doctor_class_id)
    references doctor_class;

alter table if exists doctor_class
    add constraint FKoevuee6p2vxjdcxccp24k69kr
    foreign key ("created_by_id")
    references "user";

alter table if exists doctor_class
    add constraint FKlptrv77nmjt8ep1bvi0vcmprn
    foreign key ("updated_by_id")
    references "user";

alter table if exists governorate
    add constraint FKiumtopxdtf0vwre83k6eawvol
    foreign key ("created_by_id")
    references "user";

alter table if exists governorate
    add constraint FK6lwdv65e3bkj8stmplq7dh97x
    foreign key ("updated_by_id")
    references "user";

alter table if exists medicine
    add constraint FK6pqwabnav7wci5lox4w02xfyh
    foreign key ("created_by_id")
    references "user";

alter table if exists medicine
    add constraint FKiq5wwr1lm5frprliq95cuxclb
    foreign key ("updated_by_id")
    references "user";

alter table if exists permission
    add constraint FKlgsf0luv937o3305dwoys1cei
    foreign key ("created_by_id")
    references "user";

alter table if exists permission
    add constraint FKoc4sg1cknspb1m5au9h7ofwyr
    foreign key ("updated_by_id")
    references "user";

alter table if exists pharmacy
    add constraint FKnmk0et6ldkcfek611lpih01hs
    foreign key ("created_by_id")
    references "user";

alter table if exists pharmacy
    add constraint FKedv379vhqj0ipgxdwo8b5c0go
    foreign key ("updated_by_id")
    references "user";

alter table if exists "user"
    add constraint FKafkm2kr97ap7c0nv9l59okoay
    foreign key ("created_by_id")
    references "user";

alter table if exists "user"
    add constraint FK4fol2gywb2a7tlsugg5vv9r92
    foreign key ("updated_by_id")
    references "user";

alter table if exists "user"
    add constraint FKdl9dqp078pc03g6kdnxmnlqpc
    foreign key (role_id)
    references role;
