create table tables_meta_data
(
    id              bigint generated by default as identity,
    table_name      varchar(127) not null,
    column_name     varchar(127) not null,
    column_type     varchar(127) not null,
    has_link        boolean default false,
    base_link       varchar(127),
    link_to         varchar(32),
    is_searchable   boolean default false,
    is_sortable     boolean default false,
    is_visible      boolean default false,
    column_order    integer,
    primary key (id)
);
